@startuml
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;
if (Command succeeds?) then ([yes])
    :Update in-memory AddressBook;
    :Save AddressBook to GymOps.json;
else ([no])
    :Show error message;
endif
stop
@enduml
