@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":DeleteCommandParser" as dcp LOGIC_COLOR
Participant "command:DeleteCommand" as dc LOGIC_COLOR

[-> logic : execute("delete c/1")
activate logic
logic -> abp ++: parseCommand("delete c/1")
create dcp
abp -> dcp
abp -> dcp ++: parse("c/1")
create dc
dcp -> dc ++: DeleteCommand(CLIENT, 1)
dc --> dcp --
dcp --> abp --: command
abp --> logic --: command

@enduml
